### ISSUE TITLE
Losing subscription when reconnecting

### ISSUE THREAD

**Issue by karenbajador** [beerfactory/hbmqtt#103]
I noticed that the client loses the subscriptions when reconnecting. Is there some configuration to keep the subscriptions? Or is there a way to capture reconnection attempts so that I can make the client resubscribe to the topics once connected again? TY

**Comment by karenbajador** [comment]
Setting cleansession to False when connecting did the job.

**Comment by vlcinsky** [comment]
@karenbajador Great catch. Resolved one mysterious problem on my side.

**Comment by JANEZMY** [comment]
@karenbajador thank you for your advice, fix my problem!

**Comment by JANEZMY** [comment]
@karenbajador Fixed my problem, thank you for your advice!
