### ISSUE TITLE
Websockets Version Dependency

### ISSUE THREAD

**Issue by jmattes** [beerfactory/hbmqtt#136]
For websockets you have not fixed the version you are depending on. In the most recent version of websockets, you cannot import InvalidHandshake from handshake, it seems to be appeared at version 5. However, you are trying to import it in the client which leads to an error.

**Comment by pintman** [comment]
Thanks for the hint. The following worked for me: pip install hbmqtt websockets==4.0.1

**Comment by payne92** [comment]
Dup of: #138

**Comment by njouanin** [comment]
Fix released in 0.9.3
