### ISSUE TITLE
Install failed: Build websockets

### ISSUE THREAD

**Issue by RAJensen** [beerfactory/hbmqtt#153]
Hi there.

I'm trying to get HBNQTT installed on RPi Stretch.
`sudo pip install hbmqtt`

Then it needed libpath, so that one got installed.
Then it neede websockets >=3.4
So I installed websockets 7.0
Now I'll get this error:
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QyLwwv/websockets/`

Google is not helpfull, so can anyone tell med what to now and get HBMQTT to work?

In advance thank you

**Comment by njouanin** [comment]
How did you fix this error ?

**Comment by RAJensen** [comment]
> 
> 
> How did you fix this error ?

sudo pip3 install hbmqtt

But after that, there where trouble with the mqtt messages. First it complained about the protocol and after i fixed that, there where still trouble. My message did't come through. So I did quit using it and vent for Mosquitto. That works like a charm.
