### ISSUE TITLE
Websockets aren't working

### ISSUE THREAD

**Issue by pumelo** [beerfactory/hbmqtt#20]
When connecting a client to the mqtt broker over a websocket I get the following error:

`:: WARNING :: hbmqtt.broker :: [MQTT-3.1.0-1] (client @=192.168.0.101:53088): Can't read first packet an CONNECT: No more data`

Reproduce:
Start hbmqtt broker
Connect e.g. by using this webclient: http://www.hivemq.com/demos/websocket-client/

This might be related to the following modification in websockets:
http://websockets.readthedocs.org/en/stable/changelog.html?highlight=legacy_recv
but even when using legacy websockets package I get the same behavior.

Thanks for publishing this here on github, I very much like this python mqtt broker

**Comment by pumelo** [comment]
Captured a working connection to mosquitto and the non-working one to hbmqtt with wireshark. I can see, that when upgrading the connection to a websocket, mosquitto also returns the
'Sec-WebSocket-Protocol: mqttv3.1' header. This header is not returned by hbmqtt.

No clue whether this is the reason that the connection fails ... just guessing in the dark..

**Comment by njouanin** [comment]
Hi,
I guess this is not related to websocket. As you can see on your network trace, hivemq client implements MQTT protocol version 3.1. This is incompatible with hbmqtt which only implements MQTT 3.1.1.

**Comment by pumelo** [comment]
I was using paho mqtt js client which does support both v3.1.1 and 3.1.

 as I realized:
The Paho js client first tries with the subprotocol set to "mqttv3.1" and afterwards tires with "mqtt". 

See the pull request which solved the issue for me.

**Comment by njouanin** [comment]
Thanks for you feedback. I've pulled your request, bumped to websockets to 3.0.0 and released hbmqtt 0.6.2.
