### ISSUE TITLE
Passed in event loop is not always respected

### ISSUE THREAD

**Issue by balloob** [beerfactory/hbmqtt#22]
The broker allows an event loop to be passed in but this currently raises an error. From a quick search I found two places that need to be made aware of the to be used event loop:
 - [`Session.__init__()`](https://github.com/beerfactory/hbmqtt/blob/82985b6f1ca81ca724215bd82ad00ab8fa54e74a/hbmqtt/session.py#L114-L117)
 - [`Broker.__init__()`](https://github.com/beerfactory/hbmqtt/blob/6906e7ebe28e4ec2f0b7ea7be5605c7839ef1689/hbmqtt/broker.py#L168)

**Comment by njouanin** [comment]
Hi,
Could you have a try with the commit I've just pushed to the develop branch ?

**Comment by balloob** [comment]
Did a quick test and this seems to work. Thanks!
