### ISSUE TITLE
The future of hbmqtt? Is it still maintained or EOL?

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [beerfactory/hbmqtt#235]
Hi @njouanin,

Are you still maintaining hbmqtt? I see very little activity from your side. I think hbmqtt is really a great library but it needs a little maintenance. If you do not have the capacity at the moment maybe you can let the community help you. It would be good if in that case you would add one or preferably two maintainers to this repo that can review, correct and merge critical PRs.
Of course people can take over maintenance on some fork but it would be best if this repo (and pypi) would not change and remain the master.

Software that is not maintained usually dies quite quickly and I see hbmqtt on the verge here as it is really based on outdated python support. I can only repeat: hbmqtt is really great and it would be such a shame if it did not receive any patches.

So, let's try to find a suitable maintenance strategy.
Best
Marius

**Comment by HerrMuellerluedenscheid** [comment]
ping @njouanin

**Comment by shipmints** [comment]
https://github.com/M-o-a-T/distmqtt is a fork that's been updated a bit (and you have to prefer anyio vs. asyncio). However, a quick reading shows that it has the same issues as in #237 but if it is more likely to be repaired and to accept contributions it may be time to either fork hbmqtt itself with proposed changes and corrections (and with more comprehensive tests) or look at someone else's fork. I'd hate to abandon the great work that @njouanin put into hbmqtt, though. When used with the features that are known to work, staying away from those that break #237, and using the most recent release that incorporates key fixes, it works fine for low message-rate applications. I value a pure-python implementation using as few extra dependencies as possible that is easy to reason about.

**Comment by njouanin** [comment]
Hi, I'm not maintaining this repo anymore. Please feel free to fork.

**Comment by FlorianLudwig** [comment]
@njouanin thank you for the heads-up.

Would you be willing to turn over the pypi package to a group of volunteers to maintain it?

**Comment by HerrMuellerluedenscheid** [comment]
Hi @njouanin, thanks for the info. good to know! I agree with @FlorianLudwig. It would save a lot of confusion and extra work to keep the pypi package maintained. Also, if people install unmaintained software can cause significant security risks.
Me and a colleague would be happy to start a more community driven support for hbmqtt. Anybody else interested, feel free to drop a message.

**Comment by shipmints** [comment]
@HerrMuellerluedenscheid, I'll try to lend a hand.

**Comment by shipmints** [comment]
@HerrMuellerluedenscheid not sure how quickly you want to address this. Let me know. I suppose that until @njouanin helps with an ownership transition of the existing pypi package or we elect to replace it with a new one, this initiative will be stalled.

**Comment by FlorianLudwig** [comment]
@pavandv

The python 3.8 and 3.9 support will be merged into our fork over here: https://github.com/Yakifo/aio-hbmqtt

There are a few hoops to go through first - especially securing a good new package and module name - naming is hard ;)

After having all project infrastructure setup, we will start going through the merge requests here and port them to the fork if deemed a good addition, you can follow that process here: https://github.com/Yakifo/aio-hbmqtt/issues/7

If you or anyone else here, is an expert on gitlab actions, you are welcome to fix running the tests on gitlab actions. See https://github.com/Yakifo/aio-hbmqtt/issues/11
