### ISSUE TITLE
Constant session doesn't exist warnings

### ISSUE THREAD

**Issue by jazzaj** [beerfactory/hbmqtt#39]
For each transmission of my mqtt client I see this message (with different IDs) in my logs:
`hbmqtt.broker: Delete session : session paho/AD96ADC1E3EF4820F0 doesn't exist`
For the client I use `paho.mqtt.publish.single`. The transmission of data is working fine.

Can I simply ignore the message? Do I need to look into the code of broker? Do I need to change parameters on the client?

**Comment by njouanin** [comment]
This message is logged by the broker when clean session is set to true but no previous session with this id was found. This can be ignored. I've changed this message level to DEBUG for next release.
