### ISSUE TITLE
[Question] Can I store a posts to a certain topic in a text file ? 

### ISSUE THREAD

**Issue by wolass** [beerfactory/hbmqtt#56]
Is it possible to generate a file on a server where each line is written by posting to a certain topic in hbmqtt?

In other words:  the brocker would listen to a specific topic and store the published data in a given text file.

How to do this?

**Comment by njouanin** [comment]
Hi,
The broker doesn't have this feature out of the box. Currently I see 2 ways of doing this : 
 1) Create your own python script which embeds a broker and a client. Start the broker, make the client subscribe the desired topic, and on each message received, write it in a file.
 2) Create a broker plugin which writes message to file when they are received. As an example, you can have a look at the [logging plugin](https://github.com/beerfactory/hbmqtt/blob/develop/hbmqtt/plugins/logging.py).

**Comment by ahaw021** [comment]
Thanks Muchly - was looking for something to do this :D
