### ISSUE TITLE
Memory leak using websocket protocol

### ISSUE THREAD

**Issue by gdraynz** [beerfactory/hbmqtt#62]
I encountered a memory leak using the websocket protocol `ws://` in the `WebSocketsReader.read()` method because the method `self._protocol.recv()` is blocking until a websocket message is received.
I believe this websockets library should be used with a single recv loop, otherwise you might end up stacking coroutines blocking at `recv`.
I was not able to fix it right now but the problem is definitely there. Any chance you could look into it ?

**Comment by njouanin** [comment]
May be I don't understand, but `self._protocol.recv()` is a coroutine so it doesn't block the async loop.

**Comment by gdraynz** [comment]
It blocks the coroutine until a websocket message is returned and there seems to be cases where this coroutine never ends.
I can't figure out when and why but each `read()` call will potentially blocks its coroutine indefinitely, stacking up and eating the memory on the long term.

**Comment by gdraynz** [comment]
I might have looked at the wrong place and thought each `read()` call could block its coroutine indefinitely.
Right now i'm looking at a `CancelledError` raised by the websockets lib at each ping sent by hbmqtt, but it is sometimes not raised and I monitor a bump in memory usage at the same time.
I'll keep digging. :neutral_face:

**Comment by bvansambeek** [comment]
Is this issue fixed by any recent updates?
